const MovieCategories = {
  ACTION: "ACTION",
  COMEDY: "COMEDY",
  ROMANCE: "ROMANCE",
  SCIENCE_FICTION: "SCIENCE FICTION",
  HORROR: "HORROR",
  CRIME_THRILLER: "CRIME THRILLER",
  ADVENTURE: "ADVENTURE",
  REAL_LIFE: "REAL LIFE",
};

export default MovieCategories;
